
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/jessevdk/go-flags"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/go-socks"

[[constraint]]
  name = "github.com/decred/dcrd"
  version = "1.2.0"

[[constraint]]
  name = "github.com/decred/slog"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jrick/logrotate"
  version = "1.0.0"
